# Generated by Django 5.0.7 on 2024-07-23 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('item_id', models.CharField(editable=False, max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency_id', models.CharField(max_length=10)),
                ('available_quantity', models.CharField(max_length=50)),
                ('sold_quantity', models.IntegerField(default=False)),
                ('condition', models.CharField(max_length=50)),
                ('attributes', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('status', models.CharField(max_length=50)),
                ('answer', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product')),
            ],
        ),
    ]
